general.import = [
    "/home/kyle/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[font]
size = 12

[font.bold]
family = "Terminus"
style = "Regular"

[font.bold_italic]
family = "Terminus"
style = "Regular"

[font.italic]
family = "Terminus"
style = "Regular"

[font.normal]
family = "Terminus"
style = "Regular"

[window]
dynamic_title = true

[window.padding]
x = 2
y = 2

[env]
TERM = "xterm-256color"
